### ISSUE TITLE
possible buug in hotelling.test.formula()

### ISSUE THREAD

**Issue by RLaffont** [jmcurran/Hotelling#1]
Dear Dr James Curran,

We (me and colleagues of mine) have recently used your function hotelling.test() from Hotelling Package(version 1.0-4), and if we aren't mistaken on its use, we thought about a possible bug when the 'x' argument corresponds to a formula. In this case, the function hotelling.test.formula() is called, and the problem occurs in the following lines:

    variables = mf[, -1]
    split.data = split(variables, group)

 where the response variable matrix ('variables') is split according to the levels of the factor 'group'. But using the split() function directly on the matrix 'mf' generates a list whose each element is a vector, rather than a matrix, suppressing all the mutlivariate nature of the response variable.

To see that, below a simple example on random data:

    library(Hotelling)
    y <- matrix(rnorm(1500), 300, 5) # response matrix
    f <- gl(3, 100) # factor
    h1 <- hotelling.test(y~f,  pair = c(1,2)) # uses hotelling.test.formula()
    y1 <- y[1:100, ] # response matrix for group 1
    y2 <- y[101:200, ] # response matrix for group 2
    h2 <- hotelling.test(x=y1, y=y2) # uses hotelling.test.default()
    # hotelling statistics from h1 and h2 should be the same, but it's not the case...

 A possible solution (which seems to work) to prevent this is to convert 'mf' into a dataframe before splitting:

    variables = as.data.frame(mf[, -1])
    split.data = split(variables, group)

Hope that it could be usefull for you, and thanks for your consideration.

Sincerely,

Rémi Laffont.

**Comment by jmcurran** [comment]
Thanks Remi,

I have fixed it by stopping R from making the simplification. I changed the line to

     variables = mf[, -1, drop = FALSE]

This should stop R simplifying the resulting data.frame to a matrix which is what was causing the issue. I have also made sure the print method is exported. This hopefully should get up on CRAN in the next few days.
